# Generated by Django 6.0.7 on 2026-08-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('department', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Construction', 'Construction'), ('IT & Software', 'IT & Software'), ('Healthcare', 'Healthcare'), ('Defence', 'Defence'), ('Education', 'Education'), ('Transport', 'Transport'), ('Energy', 'Energy'), ('Agriculture', 'Agriculture'), ('Insurance & Financial Services', 'Insurance & Financial Services'), ('Consultancy & Professional Services', 'Consultancy & Professional Services'), ('Manufacturing & Supply', 'Manufacturing & Supply'), ('Facility Management', 'Facility Management'), ('Telecommunications', 'Telecommunications'), ('Water & Sanitation', 'Water & Sanitation'), ('Legal & Compliance', 'Legal & Compliance'), ('Miscellaneous', 'Miscellaneous')], max_length=50)),
                ('state', models.CharField(choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OD', 'Odisha'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TS', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal'), ('DL', 'Delhi')], max_length=2)),
                ('tender_value', models.CharField(blank=True, max_length=100)),
                ('deadline', models.DateField()),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('document_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
