# Generated by Django 6.0.7 on 2026-08-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tender'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='portal_tender_id',
            field=models.CharField(blank=True, help_text="Admin-only: original portal's Tender ID for re-searching later", max_length=100),
        ),
    ]
